repos:
  - repo: https://github.com/pagopa/dx
    rev: pre_commit_scripts@0.1.0
    hooks:
      - id: lock_modules
        exclude: ^.*/(_modules|modules|\.terraform)(/.*)?$
        files: infra/(resources/prod|repository)
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
        args:
          - --args=-json
          - --args=-no-color
