yarnPath: .yarn/releases/yarn-4.1.1.cjs

nodeLinker: node-modules

packageExtensions:
  "@azure/cosmos@*":
    dependencies:
      "@azure/logger": "*"
  "express@*":
    peerDependencies:
      "ejs": "*"
