packageExtensions:
  "@azure/cosmos@*":
    dependencies:
      "@azure/logger": "*"
  eslint-plugin-perfectionist@*:
    dependencies:
      "@typescript-eslint/types": "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
