packageExtensions:
  "@azure/cosmos@*":
    dependencies:
      "@azure/logger": "*"
  express@*:
    peerDependencies:
      ejs: "*"
  "eslint-plugin-perfectionist@*":
    dependencies:
      "@typescript-eslint/types": "*"

plugins:
  - checksum: d1ffafd30894dc6b3b5c19afc983d1bcbcee0125289c9d2cb380a1a8c3748dd759edd4eac3a3724cc5851a56aa53cacf2ce705fae331d3a157cfeaf1fd5b3aa8
    path: .yarn/plugins/@yarn.build/plugin-bundle.cjs
    spec: "https://yarn.build/latest/bundle"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
