packageExtensions:
  "@azure/cosmos@*":
    dependencies:
      "@azure/logger": "*"
  eslint-plugin-perfectionist@*:
    dependencies:
      "@typescript-eslint/types": "*"
  express@*:
    peerDependencies:
      ejs: "*"
    peerDependenciesMeta:
      ejs:
        optional: true
