openapi: 3.1.0
info:
  title: openid-provider-app API
  version: 0.1.0

paths:
  /oauth/authorize:
    post:
      requestBody:
        $ref: "#/components/requestBodies/AutenticationRequest"

  /oauth/authorize/{id}:
    get:
      parameters:
        - $ref: "#/components/parameters/Id"
      responses:
        200:
          description: "Authorization"
          content:
            text/html: {}

  /interactions/{id}:
    get:
      parameters:
        - $ref: "#/components/parameters/Id"
        - in: header
          name: Accept
          required: true
          schema:
            type: string
            enum: ["application/json", "text/html"]
            default: "text/html"
      responses:
        200:
          description: "Interaction"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Interaction"
            text/html: {}
          links:
            confirm:
              operationId: confirmInteraction
              parameters:
                - name: id
                  value: $request.parameters.Id
            abort:
              operationId: abortInteraction
              parameters:
                - name: id
                  value: $request.parameters.Id

  /interactions/{id}/confirm:
    post:
      operationId: confirmInteraction
      parameters:
        - $ref: "#/components/parameters/Id"
      responses:
        303:
          description: "See Other"
          headers:
            Location:
              description: "Authorization URI"
              schema:
                type: string
                format: uri

  /interactions/{id}/abort:
    post:
      operationId: abortInteraction
      parameters:
        - $ref: "#/components/parameters/Id"

components:
  schemas:
    Callback:
      type: object
      properties:
        uri:
          type: string
        display_name:
          type: string
      required:
        - uri
        - display_name

    Institution:
      type: object
      properties:
        id:
          type: string
          format: uuid
        logo_url:
          type: string
          format: uri
        description:
          type: string
      required:
        - id
        - logo_url
        - description

    Interaction:
      type: object
      properties:
        institution:
          $ref: "#/components/schemas/Institution"
        callback:
          $ref: "#/components/schemas/Callback"
        claims:
          type: array
          prefixItems:
            - type: string
              enum: ["profile"]
          examples:
            - ["profile"]
      required:
        - institution
        - callback

  requestBodies:
    AutenticationRequest:
      description: "Authentication Request"
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            properties:
              response_type:
                type: string
                enum: ["id_token"]
              client_id:
                type: string
              redirect_uri:
                type: string
                format: uri
              scope:
                type: string
                enum: ["openid profile"]
              state:
                type: string
              nonce:
                type: string

            required:
              - response_type
              - client_id
              - redirect_uri
              - scope
              - state
              - nonce

  parameters:
    Id:
      name: id
      in: path
      required: true
      schema:
        type: string
