/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { FiscalCode } from "./FiscalCode.js";
import { Redirect } from "./Redirect.js";
import * as t from "io-ts";
import { UTCISODateFromString } from "@pagopa/ts-commons/lib/dates.js";

// required attributes
const AccessR = t.interface({
  id: t.string,

  fiscal_code: FiscalCode,

  redirect: Redirect,

  service_id: t.string,

  timestamp: UTCISODateFromString,
});

// optional attributes
const AccessO = t.partial({});

export const Access = t.exact(t.intersection([AccessR, AccessO], "Access"));

export type Access = t.TypeOf<typeof Access>;
