/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const ProblemDetailR = t.interface({});

// optional attributes
const ProblemDetailO = t.partial({
  detail: t.string,

  status: t.Integer,

  title: t.string,
});

export const ProblemDetail = t.exact(
  t.intersection([ProblemDetailR, ProblemDetailO], "ProblemDetail"),
);

export type ProblemDetail = t.TypeOf<typeof ProblemDetail>;
