/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const RedirectR = t.interface({
  display_name: t.string,

  uri: t.string,
});

// optional attributes
const RedirectO = t.partial({});

export const Redirect = t.exact(
  t.intersection([RedirectR, RedirectO], "Redirect"),
);

export type Redirect = t.TypeOf<typeof Redirect>;
