/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ValidationIssue } from "./ValidationIssue.js";
import * as t from "io-ts";
import { enumType } from "@pagopa/ts-commons/lib/types.js";

export enum TypeEnum {
  "https://pagopa.github.io/dx/problems/validation-error" = "https://pagopa.github.io/dx/problems/validation-error",
}

// required attributes
const ValidationErrorR = t.interface({
  type: enumType<TypeEnum>(TypeEnum, "type"),

  title: t.string,

  detail: t.string,

  status: t.literal(422),

  issues: t.readonlyArray(ValidationIssue, "array of ValidationIssue"),
});

// optional attributes
const ValidationErrorO = t.partial({});

export const ValidationError = t.exact(
  t.intersection([ValidationErrorR, ValidationErrorO], "ValidationError"),
);

export type ValidationError = t.TypeOf<typeof ValidationError>;
