/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const ValidationIssueR = t.interface({
  code: t.string,

  message: t.string,

  path: t.readonlyArray(t.string, "array of string"),
});

// optional attributes
const ValidationIssueO = t.partial({});

export const ValidationIssue = t.exact(
  t.intersection([ValidationIssueR, ValidationIssueO], "ValidationIssue"),
);

export type ValidationIssue = t.TypeOf<typeof ValidationIssue>;
