openapi: 3.1.0
info:
  title: relying-party-func REST API
  version: 0.1.0

paths:
  /oidc-client-configs:
    put:
      operationId: createOIDCClientConfig
      security:
        - AzureFunction: []
      requestBody:
        $ref: "#/components/requestBodies/CreateOIDCClientConfig"
      responses:
        200:
          description: "OIDC Client Configuration Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OIDCClientConfig"

components:
  securitySchemes:
    AzureFunction:
      type: apiKey
      in: header
      name: x-function-key

  requestBodies:
    CreateOIDCClientConfig:
      description: "OIDC Client Configuration"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OIDCClientConfig"

  schemas:
    OIDCClientConfig:
      type: object
      properties:
        service_id:
          $ref: "#/components/schemas/Id"
        institution_id:
          type: string
          format: uuid
        callbacks:
          type: array
          minItems: 1
          item:
            type: object
      required:
        - service_id
        - institution_id
        - callbacks
      examples:
        - {
            "service_id": "01ARZ3NDEKTSV4RRFFQ69G5FAV",
            "institution_id": "63632b50-e5c8-413b-ace0-e3f5f36068b4",
            "callbacks":
              [
                {
                  "uri": "https://io-d-openid-rp-example.azurewebsites.net/callback",
                  "display_name": "Example RP",
                },
              ],
          }

    Callback:
      type: object
      properties:
        uri:
          type: string
          format: uri
        display_name:
          type: string
          min: 3
      required:
        - uri
        - display_name
      examples:
        - { "uri": "https://", "display_name": "Mio sito" }

    Id:
      type: string
      format: ulid
      examples:
        - 01ARZ3NDEKTSV4RRFFQ69G5FAV
