openapi: 3.0.0
info:
  title: io-fims-user-func
  version: 1.0.0
  description: FIMS User Functions API

security:
  - FunctionsKey: []

paths:
  /accesses:
    get:
      summary: Get access history
      description: Get the access history for the specified user
      operationId: getAccessHistory
      parameters:
        - $ref: "#/components/parameters/user"
        - in: query
          name: page
          schema:
            type: string
          description: The page identifier
      responses:
        "200":
          description: An access history page
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessHistoryPage"
        "422":
          description: Validation error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"

  /export-requests:
    post:
      summary: Request export
      description: Request the export of the access history for the specified user
      operationId: requestExport
      parameters:
        - $ref: "#/components/parameters/user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExportRequestBody"
      responses:
        "202":
          description: The export request has been accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExportRequest"
        "409":
          description: The export request has already been requested
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
        "422":
          description: Validation error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"

components:
  securitySchemes:
    FunctionsKey:
      type: apiKey
      name: X-Functions-Key
      in: header

  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string

  schemas:
    Redirect:
      type: object
      properties:
        display_name:
          type: string
        uri:
          type: string
          format: uri
      required:
        - display_name
        - uri

    FiscalCode:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v29.1.2/openapi/definitions.yaml#/FiscalCode"

    Access:
      type: object
      properties:
        id:
          type: string
          format: ulid
        fiscal_code:
          $ref: "#/components/schemas/FiscalCode"
        redirect:
          $ref: "#/components/schemas/Redirect"
        service_id:
          type: string
          format: ulid
        timestamp:
          type: string
          format: date-time
      required:
        - id
        - fiscal_code
        - redirect
        - service_id
        - timestamp

    AccessHistoryPage:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Access"
        next:
          type: string
      required:
        - data

    ExportRequestBody:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
        - email

    ExportRequest:
      type: object
      properties:
        id:
          type: string
          format: ulid
      required:
        - id

    ProblemDetail:
      type: object
      properties:
        detail:
          type: string
        status:
          type: integer
        title:
          type: string

    ValidationIssue:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        path:
          type: array
          items:
            type: string
      required:
        - code
        - message
        - path

    ValidationError:
      type: object
      properties:
        type:
          type: string
          enum: ["https://pagopa.github.io/dx/problems/validation-error"]
        title:
          type: string
        detail:
          type: string
        status:
          type: integer
          enum: [422]
        issues:
          type: array
          items:
            $ref: "#/components/schemas/ValidationIssue"
      required:
        - type
        - title
        - detail
        - status
        - issues
