name: PR Infrastructure Plan

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/**"
      - ".github/workflows/infra-review.yaml"
      - ".github/workflows/infra-release.yaml"

jobs:
  infra_review:
    uses: pagopa/dx-typescript/.github/workflows/infra_plan.yaml@DEVEX-111-abbiamo-messo-in-sicurezza-le-pipeline-da-injection-attacks
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      region: westeurope
      base_path: "infra/resources"
      use_private_agent: true
