name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/resources/**"

jobs:
  infra_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@6086d69a207f67cab1c86024c5ec66a878ad50e4
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: true
