name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/resources/**"

jobs:
  infra_release:
    uses: pagopa/dx-typescript/.github/workflows/infra_apply.yaml@ref=DEVEX-111-abbiamo-messo-in-sicurezza-le-pipeline-da-injection-attacks
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      region: westeurope
      base_path: infra/resources
      use_private_agent: true
