name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/resources"

jobs:
  infra_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@2a6b15a40418406315ae881d3c5c5c1988630ae1
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      region: westeurope
      base_path: infra/resources
      use_private_agent: true
