name: PR Infrastructure Plan

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/**"

jobs:
  infra_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@2a6b15a40418406315ae881d3c5c5c1988630ae1
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      region: westeurope
      base_path: "infra/resources"
      use_private_agent: true
