name: Deploy (op-app)

on:
  workflow_dispatch:

jobs:
  op_app_deploy:
    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@fdc78d27c419d9ccf79799bf2769138ed247dd3d
    name: Deploy
    secrets: inherit
    with:
      workspace_name: op-app
      environment: app-prod
      resource_group_name: io-p-itn-fims-rg-01
      web_app_name: io-p-itn-fims-op-app-01
      use_staging_slot: true
      use_private_agent: true
