name: (PR) GitHub Runner

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/github-runner/prod/westeurope/**"
      - ".github/workflows/pr_github_runner.yaml"
      - ".github/workflows/call_code_review_infra.yaml"
      - ".github/workflows/call_release_infra.yaml"

jobs:
  code_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@2a6b15a40418406315ae881d3c5c5c1988630ae1
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: 'prod'
      region: 'westeurope'
      base_path: 'infra/github-runner'
