name: PR Infrastructure Plan

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      # Trigger the workflow when resources are modified
      - "infra/resources"
      # Trigger the workflow when the involved workflows are modified
      - ".github/workflows/pr_infra.yaml"
      - ".github/workflows/templates/infra_**"

concurrency:
  group: ${{ github.workflow }}

jobs:
  code_review:
    uses: ./.github/workflows/infra-plan.yaml
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      region: westeurope
      base_path: "infra/resources"
