name: (Release) Repository Settings

on:
  workflow_dispatch:
  push:
    paths:
      - "infra/repository/**"

env:
  DIR: "infra/repository"

jobs:
  code_review:
    uses: ./.github/workflows/call_release_infra.yaml
    name: Terraform Plan
    secrets: inherit
    with:
      environment: ''
      dir: ${{ env.DIR }}
      require_azure_login: false
