name: (Release) Infra WestEurope

on:
  workflow_dispatch:
  push:
    paths:
      - "infra/**/westeurope/**"
      - "infra/**/_modules"

jobs:
  release:
    uses: ./.github/workflows/call_release_infra.yaml
    name: Release Prod WestEurope
    secrets: inherit
    with:
      environment: 'prod'
      dir: 'infra/prod/westeurope'
