name: Deploy (rp-example-app)

on:
  workflow_dispatch:

jobs:
  rp_example_app_deploy:
    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@add-web-app-deploy-workflow
    name: Deploy
    secrets: inherit
    with:
      workspace_name: rp-example-app
      environment: app-prod
      resource_group_name: io-p-weu-fims-rg-01
      web_app_name: io-p-weu-fims-rp-example-app-02
      use_staging_slot: false
      use_private_agent: true
