name: (Release) GitHub Runner WestEurope

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/github-runner/**"

jobs:
  runner_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@2a6b15a40418406315ae881d3c5c5c1988630ae1
    name: Release Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      region: "westeurope"
      base_path: "infra/github-runner"
