name: (Release) GitHub Runner WestEurope

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/github-runner/**"

jobs:
  runner_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@95aa4bff8c919425be024a003cad975e6a35299c
    name: Release Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      base_path: "infra/github-runner"
