name: (PR) GitHub Runner WestEurope

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/github-runner/**"
      - ".github/workflows/pr_github_runner.yaml"

jobs:
  runner_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@95aa4bff8c919425be024a003cad975e6a35299c
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      base_path: "infra/github-runner"
